### ISSUE TITLE
Shows error each time while typing

### ISSUE THREAD

**Issue by arajparaj** [hagleitn/speed-type#3]
Each time when I start to type It is showing an error
`speed-type--diff: Symbol's function definition is void: add-face-text-property`

**Comment by hagleitn** [comment]
Seems like that specific function has been added in emacs 24.4. Your version is probably older. I'll take a look and see if I can replace it with something that doesn't require that high a version.

**Comment by hagleitn** [comment]
Alright - I've committed a fix. I think the script should now work with older versions as well (tried 23.4 and that seemed fine).
